In [1]:
import envpool
# import gymnasium as gym
import gym

In [2]:
import argparse
import os
import random
import time
from collections import deque
from distutils.util import strtobool

In [3]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.distributions.categorical import Categorical
from torch.utils.tensorboard import SummaryWriter

/mnt/harddisk1/anaconda3/envs/darl2/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, "__version__") or LooseVersion(


In [4]:
envpool.make_dm

<bound method EnvRegistry.make_dm of <envpool.registration.EnvRegistry object at 0x7ffa56cee220>>

In [5]:
classic_control_envs = [
 'CartPole-v0',
 'CartPole-v1',
 'MountainCar-v0',
 'MountainCarContinuous-v0',
 'Pendulum-v0',
 'Pendulum-v1',
 'Acrobot-v1',
 ]

In [6]:
box2d_envs = [
'BipedalWalker-v3',
 'BipedalWalkerHardcore-v3',
 'LunarLander-v2',
 'LunarLanderContinuous-v2',
]

In [7]:
dmc_envs = [
'AcrobotSwingup-v1',
 'AcrobotSwingupSparse-v1',
 'BallInCupCatch-v1',
'CartpoleBalance-v1',
 'CartpoleBalanceSparse-v1',
 'CartpoleSwingup-v1',
 'CartpoleSwingupSparse-v1',
 'CartpoleThreePoles-v1',
 'CartpoleTwoPoles-v1',
  'CheetahRun-v1',
 'FingerSpin-v1',
 'FingerTurnEasy-v1',
 'FingerTurnHard-v1',
 'FishSwim-v1',
 'FishUpright-v1',
 'HopperHop-v1',
 'HopperStand-v1',
 'HumanoidRun-v1',
 'HumanoidRunPureState-v1',
 'HumanoidStand-v1',
 'HumanoidWalk-v1',
 'HumanoidCMURun-v1',
 'HumanoidCMUStand-v1',
 'ManipulatorBringBall-v1',
 'ManipulatorBringPeg-v1',
 'ManipulatorInsertBall-v1',
 'ManipulatorInsertPeg-v1',
 'PendulumSwingup-v1',
 'PointMassEasy-v1',
 'PointMassHard-v1',
 'ReacherEasy-v1',
 'ReacherHard-v1',
 'SwimmerSwimmer6-v1',
 'SwimmerSwimmer15-v1',
 'WalkerRun-v1',
 'WalkerStand-v1',
 'WalkerWalk-v1',
]

In [8]:
mujoco_envs = [
 'Ant-v4',
 'HalfCheetah-v4',
 'Hopper-v4',
 'Humanoid-v4',
 'HumanoidStandup-v4',
 'InvertedDoublePendulum-v4',
 'InvertedPendulum-v4',
 'Pusher-v4',
 'Reacher-v4',
 'Swimmer-v4',
 'Walker2d-v4',
]

In [9]:
image_envs = [
'Adventure-v5',
 'AirRaid-v5',
 'Alien-v5',
 'Amidar-v5',
 'Assault-v5',
 'Asterix-v5',
 'Asteroids-v5',
 'Atlantis-v5',
 'Atlantis2-v5',
 'Backgammon-v5',
 'BankHeist-v5',
 'BasicMath-v5',
 'BattleZone-v5',
 'BeamRider-v5',
 'Berzerk-v5',
 'Blackjack-v5',
 'Bowling-v5',
 'Boxing-v5',
 'Breakout-v5',
 'Carnival-v5',
 'Casino-v5',
 'Centipede-v5',
 'ChopperCommand-v5',
 'CrazyClimber-v5',
 'Crossbow-v5',
 'Darkchambers-v5',
 'Defender-v5',
 'DemonAttack-v5',
 'DonkeyKong-v5',
 'DoubleDunk-v5',
 'Earthworld-v5',
 'ElevatorAction-v5',
 'Enduro-v5',
 'Entombed-v5',
 'Et-v5',
 'FishingDerby-v5',
 'FlagCapture-v5',
 'Freeway-v5',
 'Frogger-v5',
 'Frostbite-v5',
 'Galaxian-v5',
 'Gopher-v5',
 'Gravitar-v5',
 'Hangman-v5',
 'HauntedHouse-v5',
 'Hero-v5',
 'HumanCannonball-v5',
 'IceHockey-v5',
 'Jamesbond-v5',
 'JourneyEscape-v5',
 'Kaboom-v5',
 'Kangaroo-v5',
 'KeystoneKapers-v5',
 'KingKong-v5',
 'Klax-v5',
 'Koolaid-v5',
 'Krull-v5',
 'KungFuMaster-v5',
 'LaserGates-v5',
 'LostLuggage-v5',
 'MarioBros-v5',
 'MiniatureGolf-v5',
 'MontezumaRevenge-v5',
 'MrDo-v5',
 'MsPacman-v5',
 'NameThisGame-v5',
 'Othello-v5',
 'Pacman-v5',
 'Phoenix-v5',
 'Pitfall-v5',
 'Pitfall2-v5',
 'Pong-v5',
 'Pooyan-v5',
 'PrivateEye-v5',
 'Qbert-v5',
 'Riverraid-v5',
 'RoadRunner-v5',
 'Robotank-v5',
 'Seaquest-v5',
 'SirLancelot-v5',
 'Skiing-v5',
 'Solaris-v5',
 'SpaceInvaders-v5',
 'SpaceWar-v5',
 'StarGunner-v5',
 'Superman-v5',
 'Surround-v5',
 'Tennis-v5',
 'Tetris-v5',
 'TicTacToe3d-v5',
 'TimePilot-v5',
 'Trondead-v5',
 'Turmoil-v5',
 'Tutankham-v5',
 'UpNDown-v5',
 'Venture-v5',
 'VideoCheckers-v5',
 'VideoChess-v5',
 'VideoCube-v5',
 'VideoPinball-v5',
 'WizardOfWor-v5',
 'WordZapper-v5',
 'YarsRevenge-v5',
 'Zaxxon-v5',
 'CarRacing-v2',
]

In [10]:
procgen_envs = [
'BigfishEasy-v0',
 'BigfishHard-v0',
 'BossfightEasy-v0',
 'BossfightHard-v0',
 'CaveflyerEasy-v0',
 'CaveflyerHard-v0',
 'CaveflyerMemory-v0',
 'ChaserEasy-v0',
 'ChaserHard-v0',
 'ChaserExtreme-v0',
 'ClimberEasy-v0',
 'ClimberHard-v0',
 'CoinrunEasy-v0',
 'CoinrunHard-v0',
 'DodgeballEasy-v0',
 'DodgeballHard-v0',
 'DodgeballExtreme-v0',
 'DodgeballMemory-v0',
 'FruitbotEasy-v0',
 'FruitbotHard-v0',
 'HeistEasy-v0',
 'HeistHard-v0',
 'HeistMemory-v0',
 'JumperEasy-v0',
 'JumperHard-v0',
 'JumperMemory-v0',
 'LeaperEasy-v0',
 'LeaperHard-v0',
 'LeaperExtreme-v0',
 'MazeEasy-v0',
 'MazeHard-v0',
 'MazeMemory-v0',
 'MinerEasy-v0',
 'MinerHard-v0',
 'MinerMemory-v0',
 'NinjaEasy-v0',
 'NinjaHard-v0',
 'PlunderEasy-v0',
 'PlunderHard-v0',
 'StarpilotEasy-v0',
 'StarpilotHard-v0',
 'StarpilotExtreme-v0',
  'Catch-v0',
]

In [11]:
toy_envs = [ 'FrozenLake-v1',
 'FrozenLake8x8-v1',
 'Taxi-v3',
 'NChain-v0',
 'CliffWalking-v0',
 'Blackjack-v1',]

In [12]:
vis_doom_envs = ['D1Basic-v1',
 'D2Navigation-v1',
 'D3Battle-v1',
 'D4Battle2-v1',
 'Basic-v1',
 'Cig-v1',
 'DeadlyCorridor-v1',
 'Deathmatch-v1',
 'DefendTheCenter-v1',
 'DefendTheLine-v1',
 'HealthGathering-v1',
 'HealthGatheringSupreme-v1',
 'MultiDuel-v1',
 'MyWayHome-v1',
 'PredictPosition-v1',
 'RocketBasic-v1',
 'SimplerBasic-v1',
 'TakeCover-v1',
 'VizdoomCustom-v1']

In [13]:
lst = [
  # 
  'CartPole-v1',
 'MountainCar-v0',
 'MountainCarContinuous-v0',
 'Pendulum-v1',
 'Acrobot-v1',
  # box2d
  'BipedalWalker-v3',
 'BipedalWalkerHardcore-v3',
 'LunarLander-v2',
 'LunarLanderContinuous-v2',
 # mujoco
 'Ant-v4',
 'HalfCheetah-v4',
 'Hopper-v4',
 'Humanoid-v4',
 'HumanoidStandup-v4',
 'InvertedDoublePendulum-v4',
 'InvertedPendulum-v4',
 'Pusher-v4',
 'Reacher-v4',
 'Swimmer-v4',
 'Walker2d-v4',
 # dmc
'AcrobotSwingup-v1',
#  'AcrobotSwingupSparse-v1',
 'BallInCupCatch-v1',
'CartpoleBalance-v1',
#  'CartpoleBalanceSparse-v1',
 'CartpoleSwingup-v1',
#  'CartpoleSwingupSparse-v1',
 'CartpoleThreePoles-v1',
 'CartpoleTwoPoles-v1',
  'CheetahRun-v1',
 'FingerSpin-v1',
 'FingerTurnEasy-v1',
 'FingerTurnHard-v1',
 'FishSwim-v1',
 'FishUpright-v1',
 'HopperHop-v1',
 'HopperStand-v1',
 'HumanoidRun-v1',
 'HumanoidRunPureState-v1',
 'HumanoidStand-v1',
 'HumanoidWalk-v1',
 'HumanoidCMURun-v1',
 'HumanoidCMUStand-v1',
 'ManipulatorBringBall-v1',
 'ManipulatorBringPeg-v1',
 'ManipulatorInsertBall-v1',
 'ManipulatorInsertPeg-v1',
 'PendulumSwingup-v1',
 'PointMassEasy-v1',
 'PointMassHard-v1',
 'ReacherEasy-v1',
 'ReacherHard-v1',
 'SwimmerSwimmer6-v1',
 'SwimmerSwimmer15-v1',
 'WalkerRun-v1',
 'WalkerStand-v1',
 'WalkerWalk-v1', ]
len(lst)

54

In [14]:
envpool.list_all_envs()

['Adventure-v5',
 'AirRaid-v5',
 'Alien-v5',
 'Amidar-v5',
 'Assault-v5',
 'Asterix-v5',
 'Asteroids-v5',
 'Atlantis-v5',
 'Atlantis2-v5',
 'Backgammon-v5',
 'BankHeist-v5',
 'BasicMath-v5',
 'BattleZone-v5',
 'BeamRider-v5',
 'Berzerk-v5',
 'Blackjack-v5',
 'Bowling-v5',
 'Boxing-v5',
 'Breakout-v5',
 'Carnival-v5',
 'Casino-v5',
 'Centipede-v5',
 'ChopperCommand-v5',
 'CrazyClimber-v5',
 'Crossbow-v5',
 'Darkchambers-v5',
 'Defender-v5',
 'DemonAttack-v5',
 'DonkeyKong-v5',
 'DoubleDunk-v5',
 'Earthworld-v5',
 'ElevatorAction-v5',
 'Enduro-v5',
 'Entombed-v5',
 'Et-v5',
 'FishingDerby-v5',
 'FlagCapture-v5',
 'Freeway-v5',
 'Frogger-v5',
 'Frostbite-v5',
 'Galaxian-v5',
 'Gopher-v5',
 'Gravitar-v5',
 'Hangman-v5',
 'HauntedHouse-v5',
 'Hero-v5',
 'HumanCannonball-v5',
 'IceHockey-v5',
 'Jamesbond-v5',
 'JourneyEscape-v5',
 'Kaboom-v5',
 'Kangaroo-v5',
 'KeystoneKapers-v5',
 'KingKong-v5',
 'Klax-v5',
 'Koolaid-v5',
 'Krull-v5',
 'KungFuMaster-v5',
 'LaserGates-v5',
 'LostLuggage-v5',

In [15]:
num_envs = 96
batch_size = 48

In [16]:
envs = make_ba

NameError: name 'make_ba' is not defined

In [ ]:
aspace = envs.action_space

In [ ]:
aspace.low

array([-1., -1., -1., -1., -1., -1.])

In [ ]:
# envs.async_reset()

In [ ]:
# obs, rew, terminated, truncated, info = envs.recv()


In [ ]:
# print(obs.shape)
# print(rew.shape)
# print(terminated.shape)
# print(truncated.shape)
# print(info)


In [ ]:
# print(type(obs))

In [ ]:
# envs.send(action, env_id)   


In [ ]:
# obs, rew, terminated, truncated, info = envs.recv()

In [ ]:
# print(obs.shape)
# print(rew.shape)
# print(terminated.shape)
# print(truncated.shape)
# print(info)


In [ ]:
# total_rewards = 0
# for step in range(0, 1000):
#     obs, rew, terminated, truncated, info = envs.recv()
#     env_id = info["env_id"]
#     total_rewards += rew
#     action =- np.random.randn(48, 6) 
#     envs.send(action, env_id)   

In [ ]:
# total_rewards

In [24]:
from omegaconf import OmegaConf

cfg_path = "/home/kukjin/Projects/DARL_transformer/configs/sac_trainer.yaml"
nn_cfg_path = "/home/kukjin/Projects/DARL_transformer/configs/nn/nn.yaml"
sac_cfg_path = "/home/kukjin/Projects/DARL_transformer/configs/sac/sac.yaml"
ccnn_cfg_img_path = "/home/kukjin/Projects/DARL_transformer/configs/ccnn_img/ccnn_img.yaml"
ccnn_cfg_seq_path = "/home/kukjin/Projects/DARL_transformer/configs/ccnn_seq/ccnn_seq.yaml"

cfg = OmegaConf.load(cfg_path)
nn_cfg = OmegaConf.load(nn_cfg_path)
sac_cfg = OmegaConf.load(sac_cfg_path)
ccnn_seq_cfg = OmegaConf.load(ccnn_cfg_img_path)
ccnn_img_cfg = OmegaConf.load(ccnn_cfg_seq_path)

cfg.nn = nn_cfg
cfg.sac = sac_cfg
cfg.ccnn_seq = ccnn_seq_cfg
cfg.ccnn_img = ccnn_img_cfg

cfg

{'defaults': [{'sac': 'sac'}, {'nn': 'nn'}, {'ccnn_img': 'ccnn_img'}, {'ccnn_seq': 'ccnn_seq'}, '_self_'], 'hydra': {'run': {'dir': 'outputs/${now:%Y-%m-%d/%H-%M-%S}'}}, 'experiment': {'seed': 42, 'num_envs': 1, 'total_timesteps': 10000000, 'save_ckpt': False, 'num_checkpoints': 20, 'print_interval': 100, 'stop_after_epochs': 500, 'capture_video': False, 'device': 4, 'cuda': True, 'torch_deterministic': True, 'resume': False, 'resume_update_idx': 0, 'resume_dir': 'None', 'env_ids': ['CartPole-v1', 'Pendulum-v1', 'Acrobot-v1', 'BipedalWalker-v3', 'LunarLander-v2', 'HalfCheetah-v4', 'Ant-v4', 'Hopper-v4', 'Walker2d-v4']}, 'evaluation': {'eval_seed': 3142, 'every': 2, 'num_eval': 5, 'num_test_envs': 5}, 'wandb': {'mode': 'online', 'project': 'DomainAgnosticRL', 'entity': None, 'name': None, 'group': None, 'tags': None, 'notes': None}, 'paths': {'dir': 'outputs/${now:%Y-%m-%d/%H-%M-%S}', 'log': 'outputs/${now:%Y-%m-%d/%H-%M-%S}/runs', 'video': 'outputs/${now:%Y-%m-%d/%H-%M-%S}/videos', 'ch

In [17]:
from modules.utils import set_seed, make_batched_env

In [18]:
train_envs = make_batched_env(0, "CartPole-v1", cfg, mode='train')


NameError: name 'cfg' is not defined

In [ ]:
obs = train_envs.reset()

In [19]:
obs.shape

NameError: name 'obs' is not defined

In [ ]:
action = np.array([train_envs.action_space.sample()])
action

array([1])

In [ ]:
next_obs, reward, done, info = train_envs.step(action)

In [20]:
done

NameError: name 'done' is not defined

In [21]:
info

NameError: name 'info' is not defined

In [22]:
while not done:
    next_obs, reward, done, info = train_envs.step(action)

NameError: name 'done' is not defined

In [23]:
done

NameError: name 'done' is not defined

In [29]:
info

{'env_id': array([0], dtype=int32),
 'players': {'env_id': array([0], dtype=int32)},
 'TimeLimit.truncated': array([False]),
 'elapsed_step': array([10], dtype=int32),
 'r': array([10.], dtype=float32),
 'l': array([10], dtype=int32)}

In [30]:
next_obs

array([[ 2.02353746,  1.58320824, -2.03221809, -1.64123075]])

In [39]:
from modules.utils import make_env
import gym 

envs = gym.vector.SyncVectorEnv([make_env(cfg, 'CartPole-v1', idx=0, evaluation=False) for i in range(2)])

/mnt/harddisk1/anaconda3/envs/darl2/lib/python3.9/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/mnt/harddisk1/anaconda3/envs/darl2/lib/python3.9/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/mnt/harddisk1/anaconda3/envs/darl2/lib/python3.9/site-packages/gym/vector/vector_env.py:56: DeprecationWarning: WARN: Initializing vector env in old step API which returns one bool array instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [40]:
np.__version__

'1.23.5'

In [41]:
envs

SyncVectorEnv(2)

In [42]:
obs = envs.reset()

In [43]:
obs

array([[-2.2251571e-04,  3.3074312e-04,  7.5834185e-05,  5.0558316e-05],
       [-3.2398480e-04, -2.2660602e-04,  2.5068814e-04,  1.4974874e-04]],
      dtype=float32)

In [49]:
action = np.array([envs.single_action_space.sample()for i in range(2)])
action

array([1, 0])

In [50]:
next_obs, reward, done, info = envs.step(action)

In [51]:
done

array([False, False])

In [52]:
info

{}

In [56]:
gym.__version__

'0.25.1'

In [54]:
for i in range(100):
    next_obs, reward, done, info = envs.step(action)
    for d in done:
        if d:
            print(info)
    

{'episode': array([None, {'r': 9.0, 'l': 9, 't': 123.405781}], dtype=object), '_episode': array([False,  True]), 'final_observation': array([None, array([-1.97899846, -1.56777388,  1.99848512,  1.61185734])],
      dtype=object), '_final_observation': array([False,  True])}
{'episode': array([{'r': 10.0, 'l': 10, 't': 123.411076}, None], dtype=object), '_episode': array([ True, False]), 'final_observation': array([array([ 1.99973084,  1.58265535, -2.03060651, -1.63937563]), None],
      dtype=object), '_final_observation': array([ True, False])}
{'episode': array([{'r': 8.0, 'l': 8, 't': 123.421983},
       {'r': 9.0, 'l': 9, 't': 123.420482}], dtype=object), '_episode': array([ True,  True]), 'final_observation': array([array([ 1.67000423,  1.12898201, -1.68792071, -1.27861417]),
       array([-1.42158335, -1.58141554,  1.72738386,  1.54252334])],
      dtype=object), '_final_observation': array([ True,  True])}
{'episode': array([{'r': 8.0, 'l': 8, 't': 123.421983},
       {'r': 9.0,

In [57]:
next_obs.shape

(2, 4)

In [55]:
info

{}

In [38]:
info

{'episode': array([{'r': 9.0, 'l': 9, 't': 87.609964}], dtype=object),
 '_episode': array([ True]),
 'final_observation': array([array([ 1.97739346,  1.56827127, -1.99502061, -1.61416257])],
       dtype=object),
 '_final_observation': array([ True])}

In [37]:
next_obs

array([[-0.953111  , -1.3369913 ,  0.59857225,  1.3254138 ]],
      dtype=float32)

In [12]:
env_id = info["env_id"]

In [13]:
env_id

array([12, 46, 11,  0,  1,  9,  2, 44,  7,  3,  4, 10, 18, 45,  5,  6,  8,
       22, 32, 17, 31, 15, 43, 21, 16, 33, 26, 14, 41, 27, 48, 40, 38, 13,
       36, 25, 42, 23, 24, 35, 37, 39, 29, 20, 19, 28, 34, 30],
      dtype=int32)

In [14]:
envs.action_space.shape

(6,)

In [24]:
action = np.random.randint(num_discrete, size=len(env_id))
action.shape

(48,)

In [29]:
action = np.random.randn(batch_size, 6)
action.shape

(48, 6)

In [ ]:
next_obs, reward, done, info = envs.step(action)

: 

: 

In [18]:
timestep = envs.recv()

In [38]:
timestep

(array([[-2.75850446e-02,  4.51912027e-02,  5.99013531e-01,
         -6.25943275e-01, -2.33137660e-01,  7.37281991e-01,
         -6.04216535e-01,  1.01188626e-01, -2.01178381e-02,
         -9.58564003e-01, -6.88572682e-01,  2.46636450e+00,
          1.40208049e+00,  2.61078729e-01, -1.19076639e+00,
          9.34845213e-01,  1.01417438e+00],
        [-6.58746098e-02, -3.24351743e-02, -3.86323775e-01,
          4.25289630e-02, -4.27119728e-01,  1.44880784e-01,
         -3.86953896e-01,  3.93412291e-01, -2.34852801e-01,
         -1.35083835e+00,  7.53410677e-02, -3.01407919e+00,
         -1.82718418e+00,  7.22767407e-01,  1.19283306e+00,
         -9.09645525e-01,  3.36173270e+00],
        [ 2.28402885e-02,  7.17677297e-02,  5.59843555e-01,
         -6.24382018e-01, -4.19593209e-01,  5.24821574e-01,
          5.26942752e-02,  5.29925367e-01,  3.50279461e-01,
         -1.45252789e+00, -2.84421767e-01,  1.33070514e+00,
          5.90828324e-01,  3.05266272e-01,  4.25040298e+00,
          2.

In [35]:
print(next_obs.shape)
print(reward.shape)
print(terminated.shape)
print(truncated.shape)
print(info)
env_id = info['env_id']



(48, 17)
(48,)
(48,)
(48,)
{'env_id': array([26, 28, 39, 31, 44, 36, 35, 41, 45, 42, 56, 43, 53, 55, 50, 52, 66,
       58, 57, 67, 68, 77, 88, 78, 83, 80, 79, 85, 94, 95, 76, 91, 69, 71,
       75, 82, 74, 70, 90, 89, 81, 86, 92, 93, 84, 87, 72, 73],
      dtype=int32), 'players': {'env_id': array([26, 28, 39, 31, 44, 36, 35, 41, 45, 42, 56, 43, 53, 55, 50, 52, 66,
       58, 57, 67, 68, 77, 88, 78, 83, 80, 79, 85, 94, 95, 76, 91, 69, 71,
       75, 82, 74, 70, 90, 89, 81, 86, 92, 93, 84, 87, 72, 73],
      dtype=int32)}, 'reward_run': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'reward_ctrl': array([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0.,

In [7]:
envs.action_space

Box(-1.0, 1.0, (6,), float64)

In [8]:
actions = np.stack([envs.action_space.sample() for i in range(num_envs)])

In [9]:
actions.shape

(96, 6)

In [10]:
envs.num_envs = num_envs
envs.single_action_space = envs.action_space
envs.single_observation_space = envs.observation_space

In [11]:
obs, info = envs.reset()

In [12]:
obs

array([[-0.06331304,  0.0559382 ,  0.01937003, -0.01083345, -0.08000502,
        -0.00815022, -0.03325828, -0.07142664, -0.04826188,  0.01641648,
         0.02330952,  0.01179946,  0.14623781,  0.15387149, -0.24391058,
         0.06034413, -0.0251044 ],
       [ 0.08193413,  0.06468624, -0.02558732,  0.09565195,  0.08663149,
        -0.02088608, -0.03870237, -0.05387886,  0.02371703,  0.2275385 ,
        -0.16784505, -0.11577671,  0.08786311,  0.07599991,  0.1007009 ,
        -0.1083888 ,  0.1400508 ],
       [ 0.03684346,  0.08346798, -0.05901319,  0.09793726,  0.0437633 ,
        -0.08249156, -0.02118757, -0.0899881 , -0.06478368, -0.05519389,
        -0.07100642,  0.09528173, -0.09723472,  0.04562799,  0.28555246,
         0.0698644 ,  0.05275544],
       [-0.09364504,  0.0255701 , -0.06311626, -0.04072481, -0.04860649,
         0.03598501, -0.04348796,  0.08336848,  0.05486146, -0.12175255,
         0.01550792,  0.14191162, -0.04170158, -0.04204625, -0.06476628,
         0.15115428

In [13]:
info


{'env_id': array([ 0,  5,  4,  2,  1,  6, 12, 10, 31, 27,  9, 35, 29, 11, 23, 32, 33,
        30,  7,  3,  8, 40, 15, 42, 41, 22, 44, 39, 43, 24, 17, 38, 34, 20,
        18, 16, 19, 13, 14, 36, 26, 25, 45, 37, 48, 46, 50, 47],
       dtype=int32),
 'players': {'env_id': array([ 0,  5,  4,  2,  1,  6, 12, 10, 31, 27,  9, 35, 29, 11, 23, 32, 33,
         30,  7,  3,  8, 40, 15, 42, 41, 22, 44, 39, 43, 24, 17, 38, 34, 20,
         18, 16, 19, 13, 14, 36, 26, 25, 45, 37, 48, 46, 50, 47],
        dtype=int32)},
 'reward_run': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'reward_ctrl': array([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        -0., -0., -0.,

In [14]:
device = "cuda:5"

In [15]:
global_step = 0
start_time = time.time()
next_obs, info = envs.reset()
next_obs = torch.Tensor(next_obs).to(device)
next_done = torch.zeros(num_envs).to(device)


/home/kukjin/.conda/envs/test_env/lib/python3.10/site-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [16]:
total_timesteps = 1000000
global_step = 0

In [17]:
import inspect

In [18]:
signature = inspect.signature(envs.action_space.sample)
print(signature)

(mask: 'None' = None) -> 'NDArray[Any]'


In [19]:
signature = vars(envs.action_space.sample)
print(signature)

{}


In [20]:
%%timeit
total_rewards = 0
obs, info = envs.reset()
for step in range(0, 1000):
    # action = envs.action_space.sample()
    actions = np.stack([envs.action_space.sample() for i in range(num_envs)])
    next_obs, reward, terminated, truncated, info = envs.step(actions)
    total_rewards += np.mean(reward)
    done = np.logical_or(terminated, truncated)
    next_obs, next_done = torch.Tensor(next_obs).to(device), torch.Tensor(done).to(device)
print(f"total_rewards: {total_rewards}")

: 

: 

In [ ]:
def make_env(env_id):
    def thunk():
        env = gym.make(env_id)
        return env
    return thunk

In [ ]:
gym_envs = gym.vector.SyncVectorEnv(
        [make_env("HalfCheetah-v4") for i in range(num_envs)]
    )

<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead


In [ ]:
gym_envs.action_space.sample().shape

(96, 6)

In [ ]:
%%timeit
total_rewards = 0
obs, info = gym_envs.reset()
for step in range(0, 1000):
    actions = gym_envs.action_space.sample()
    next_obs, reward, terminated, truncated, info = gym_envs.step(actions)
    total_rewards += np.mean(reward)
    done = np.logical_or(terminated, truncated)
    next_obs, next_done = torch.Tensor(next_obs).to(device), torch.Tensor(done).to(device)
print(f"total_rewards: {total_rewards}")


total_rewards: -279.1630750078215
total_rewards: -271.102743936323
total_rewards: -298.7254640804569
total_rewards: -287.2895548141525
total_rewards: -292.94488184294244
total_rewards: -263.3168568749372
total_rewards: -283.7712929465664
total_rewards: -281.5529480138204
7.69 s ± 115 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [66]:
from gym.spaces import Box, Discrete


In [70]:
class FlattenObsWrapper(gym.Wrapper):
    def __init__(self, env):
        size, highs, lows = self.get_obs_space(env.observation_space)
        self.observation_space = Box(low=lows, high=highs)
        
    def reset(self, **kwargs):
        observations = super().reset(**kwargs)
        if isinstance(type(observations, Dict)):
            observations =  self.flatten_dict(observations)
        return observations
    
    def flatten_dict(self, obs):
        features = []
        for key, values in obs.items():
            features.append(values)
        return np.concatenate(features, axis=-1)

    def get_obs_space(self, observation_space):
        shapes = []
        highs = []
        lows = []
    
        for key, box in observation_space.items():
            shapes.append(box.shape)
            highs.append(box.high)
            lows.append(box.low)
        size = (np.sum(shapes, dtype=np.int32))
        highs = np.concatenate(highs, axis=-1)
        lows = np.concatenate(lows, axis=-1)        
        return size, highs, lows

In [76]:
dones = torch.zeros(10)
dones

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
dones[1:] = 1
dones

tensor([0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
False in dones

True

In [81]:
dones[0] = 1

In [82]:
False in dones

False

In [71]:
# envpool_env = envpool.make("HopperHop-v1", num_envs=1)
envs = envpool.make(
    "HopperHop-v1",
    # "CartpoleBalance-v1", 
    env_type="gym",
    num_envs=5,
    # num_threads=16,
    seed=42,
)

# # if _ is in the original name
# suite.load("ball_in_cup", "catch")
# # equal to
# envpool.make_dm("BallInCupCatch-v1", num_envs=1)

In [72]:
flatten_envs = FlattenObsWrapper(envs)

/home/kukjin/.conda/envs/test_env/lib/python3.10/site-packages/gym/spaces/box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


In [73]:
flatten_envs.observation_space

Box(0.0, inf, (15,), float32)

In [74]:
obs = flatten_envs.reset()

RecursionError: maximum recursion depth exceeded while calling a Python object

In [16]:
envs.observation_space

Dict(position:Box(2.2250738585072014e-308, 1.7976931348623157e+308, (6,), float64), velocity:Box(2.2250738585072014e-308, 1.7976931348623157e+308, (7,), float64), touch:Box(2.2250738585072014e-308, 1.7976931348623157e+308, (2,), float64))

In [6]:
envs.observation_space["position"].shape

(6,)

In [17]:
for key, value in envs.observation_space.items():
    print(value)
    print(value.high)
    print(value.low)
    

Box(2.2250738585072014e-308, 1.7976931348623157e+308, (6,), float64)
[1.79769313e+308 1.79769313e+308 1.79769313e+308 1.79769313e+308
 1.79769313e+308 1.79769313e+308]
[2.22507386e-308 2.22507386e-308 2.22507386e-308 2.22507386e-308
 2.22507386e-308 2.22507386e-308]
Box(2.2250738585072014e-308, 1.7976931348623157e+308, (7,), float64)
[1.79769313e+308 1.79769313e+308 1.79769313e+308 1.79769313e+308
 1.79769313e+308 1.79769313e+308 1.79769313e+308]
[2.22507386e-308 2.22507386e-308 2.22507386e-308 2.22507386e-308
 2.22507386e-308 2.22507386e-308 2.22507386e-308]
Box(2.2250738585072014e-308, 1.7976931348623157e+308, (2,), float64)
[1.79769313e+308 1.79769313e+308]
[2.22507386e-308 2.22507386e-308]


In [8]:
np.sum([])

0.0

In [53]:
def get_obs_space(observation_space):
    shapes = []
    highs = []
    lows = []
    
    for key, box in observation_space.items():
        shapes.append(box.shape)
        highs.append(box.high)
        lows.append(box.low)
    size = (np.sum(shapes, dtype=np.int32))
    highs = np.concatenate(highs, axis=-1)
    lows = np.concatenate(lows, axis=-1)        
            
    return size, highs, lows

In [54]:
size, highs, lows = get_obs_space(envs.observation_space)

In [62]:
lows

array([2.22507386e-308, 2.22507386e-308, 2.22507386e-308, 2.22507386e-308,
       2.22507386e-308, 2.22507386e-308, 2.22507386e-308, 2.22507386e-308,
       2.22507386e-308, 2.22507386e-308, 2.22507386e-308, 2.22507386e-308,
       2.22507386e-308, 2.22507386e-308, 2.22507386e-308])

In [58]:
size

15

In [56]:
highs

array([1.79769313e+308, 1.79769313e+308, 1.79769313e+308, 1.79769313e+308,
       1.79769313e+308, 1.79769313e+308, 1.79769313e+308, 1.79769313e+308,
       1.79769313e+308, 1.79769313e+308, 1.79769313e+308, 1.79769313e+308,
       1.79769313e+308, 1.79769313e+308, 1.79769313e+308])

In [63]:
a = Box(low=lows, high=highs)

/home/kukjin/.conda/envs/test_env/lib/python3.10/site-packages/gym/spaces/box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


In [64]:
a.low

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [72]:
tuples = get_obs_space(envs.observation_space)

In [73]:
total_tuple = ()
for tuple_ in tuples:
    total_tuple += tuple_

In [74]:
total_tuple

(6, 7, 2)

In [62]:
Box(15)

TypeError: Box.__init__() missing 1 required positional argument: 'high'

In [51]:
envs.action_space

Box(-1.0, 1.0, (4,), float64)

In [47]:
def flatten_dict(obs):
    features = []
    for key, values in obs.items():
        features.append(values)
    return np.concatenate(features, axis=-1)

In [48]:
flatten = flatten_dict(obs)

In [49]:
flatten.shape

(5, 15)

In [39]:
obs = envs.reset()
obs

{'position': array([[ 0.        ,  1.86323452, -0.33150631, -0.51758822,  1.59773153,
         -0.08508571],
        [ 0.        , -0.01972107, -0.41582669, -2.49967641,  0.52288706,
          0.48857482],
        [ 0.        , -0.42385296, -0.49032428, -0.9946092 ,  0.55397992,
         -0.31985195],
        [ 0.        , -1.22813377,  0.17957309, -1.6471557 ,  2.50981144,
          0.65131587],
        [ 0.        , -1.52023665,  0.19291191, -0.08515145,  0.60589868,
          0.76919748]]),
 'velocity': array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]),
 'touch': array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])}

In [40]:
for key, values in obs.items():
    print(values.shape)


(5, 6)
(5, 7)
(5, 2)


In [36]:
obs = envs.reset()
obs

{'position': array([[ 0.        ,  1.86323452, -0.33150631, -0.51758822,  1.59773153,
         -0.08508571],
        [ 0.        , -0.01972107, -0.41582669, -2.49967641,  0.52288706,
          0.48857482]]),
 'velocity': array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]),
 'touch': array([[0., 0.],
        [0., 0.]])}

In [25]:
obs.joint_angles

AttributeError: 'dict' object has no attribute 'joint_angles'

In [23]:
from torchvision.transforms.functional import to_tensor

In [24]:
obs = to_tensor(obs)

TypeError: pic should be PIL Image or ndarray. Got <class 'dict'>

In [21]:
type(obs)

dict

In [18]:
def flatten_dict(obs_dict, parent_key='', sep='/'):
    flattened_dict = {}
    for key, value in obs_dict.items():
        new_key = f"{parent_key}{sep}{key}" if parent_key else key
        if isinstance(value, dict):
            flattened_dict.update(flatten_dict(value, new_key, sep=sep))
        else:
            flattened_dict[new_key] = value
    return flattened_dict

# Example usage:
# observation_dict = {
#     'player': {
#         'position': [1, 2, 3],
#         'velocity': [0.5, 0.1, -0.3]
#     },
#     'world': {
#         'time': 100,
#         'score': 50
#     }
# }

flattened_dict = flatten_dict(obs)
print(flattened_dict)

{'position': array([[ 0.        ,  1.86323452, -0.33150631, -0.51758822,  1.59773153,
        -0.08508571]]), 'velocity': array([[0., 0., 0., 0., 0., 0., 0.]]), 'touch': array([[0., 0.]])}
