In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.linalg import matrix_norm

In [5]:
weights = torch.ones([128, 6, 64])

In [13]:
import math
math.sqrt(6*64)

19.595917942265423

In [7]:
norm = matrix_norm(weights, ord='fro', dim=(-2, -1))

In [10]:
norm.shape

torch.Size([128])

In [15]:
norm

tensor([19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959, 19.5959,
        19.5959, 19.5959, 19.5959, 19.59

In [44]:
LOG_STD_MIN = -5
LOG_STD_MAX = 1

In [45]:
a_mu = torch.zeros([32, 6])
a_logstd = torch.ones([32, 6])

In [46]:
a_logstd = LOG_STD_MIN + 0.5 * (LOG_STD_MAX - LOG_STD_MIN) * (a_logstd + 1)

In [47]:
a_logstd

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1

In [48]:
from torch.distributions import Normal

In [49]:
a_std = a_logstd.exp()

In [50]:
a_std

tensor([[2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.718

In [33]:
dist = Normal(a_mu, a_std)

In [35]:
entropy = dist.entropy().sum(-1)

In [36]:
entropy

tensor([26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136,
        26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136,
        26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136,
        26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136, 26.5136])