In [1]:
import torch

In [8]:
A = torch.tensor([[1., 2.,],
                  [3., 4.]])
B = torch.tensor([[0., 2.,],
                  [-3., 1.]])

In [19]:
C = torch.tensordot(A, B)
C

tensor(-1.)

In [10]:
sim = C / torch.linalg.matrix_norm(A, ord='fro') / torch.linalg.matrix_norm(B, ord='fro')

In [ ]:
def mat_cos_similarity(M1, M2):
    return torch.tensordot(M1, M2) / torch.linalg.matrix_norm(M1, ord='fro') / torch.linalg.matrix_norm(M2, ord='fro')

In [12]:
sim

tensor(-0.0488)

In [13]:
sim2 = torch.trace(A @ B.T) / (torch.sqrt(torch.trace(A@A.T) * torch.trace(B@B.T)))


In [14]:
sim2

tensor(-0.0488)

In [17]:
torch.sqrt(torch.trace(A@A.T))

tensor(5.4772)

In [18]:
torch.linalg.matrix_norm(A, ord='fro') 

tensor(5.4772)

In [20]:
torch.trace(A @ B.T)

tensor(-1.)

In [23]:
torch.nn.functional.cosine_similarity(A, B, dim=1)

tensor([ 0.8944, -0.3162])

In [24]:
a = torch.flatten(A)
b = torch.flatten(B)

In [26]:
print(a)

tensor([1., 2., 3., 4.])


In [27]:
torch.nn.functional.cosine_similarity(a, b, dim=0)

tensor(-0.0488)

In [34]:
c = torch.tensor([[1., 2., 3., 4.]])
d = -1 * torch.tensor([[1., 2., 3., 5.]])

sim3 = torch.nn.functional.cosine_similarity(c, d, dim=1)
sim3

tensor([-0.9940])

In [35]:
sim4 = torch.trace(c @ d.T) / (torch.sqrt(torch.trace(c@c.T) * torch.trace(d@d.T)))
sim4

tensor(-0.9940)

In [ ]:
def f(x, y):
    return 2*x*y / (x + y)

In [36]:
def mat_cos_similarity(M1, M2):
    return torch.tensordot(M1, M2) / torch.linalg.matrix_norm(M1, ord='fro') / torch.linalg.matrix_norm(M2, ord='fro')

In [37]:
mat_cos_similarity(c, d)

tensor(-0.9940)

In [ ]:

  1
    1
      1

In [1]:
lst = [1, 2, 3, 4]
results = [(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]

In [2]:
from itertools import combinations

In [3]:
for c in combinations(lst, 2):
    print(c)

(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


In [4]:
env_ids = [
 'Breakout-v5',
  'CartPole-v1',
 'MountainCar-v0',
 'MountainCarContinuous-v0',
 'Pendulum-v1',
 'Acrobot-v1',]
  

In [7]:
index_tuple__combinations = [ind_tup for ind_tup in combinations(range(len(env_ids)), 2)]


In [8]:
index_tuple__combinations

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (2, 3),
 (2, 4),
 (2, 5),
 (3, 4),
 (3, 5),
 (4, 5)]

In [14]:
a = index_tuple__combinations[0][::-1]
a

(1, 0)